DROP TABLE IF EXISTS Compte CASCADE;
DROP TABLE IF EXISTS Profil CASCADE;
DROP TABLE IF EXISTS Personne CASCADE;
DROP TABLE IF EXISTS Personnage CASCADE;
DROP TABLE IF EXISTS Video CASCADE;
DROP TABLE IF EXISTS Visionnage CASCADE;
DROP TABLE IF EXISTS attribue CASCADE;
DROP TABLE IF EXISTS joue CASCADE;
DROP TABLE IF EXISTS note CASCADE;


/*DROP TABLE IF EXISTS Serie CASCADE;*/
/*DROP TABLE IF EXISTS Label CASCADE;*/